[tool.isort]
add_imports = ["from __future__ import annotations"]
force_grid_wrap = 2
multi_line_output = 3
include_trailing_comma = true
quiet = true

[tool.ruff]
line-length = 120

# Exclude TOML file from ruff check as it contains jinja syntax that fails toml parser
exclude = [
    "*/pyproject.toml",
    "*/.venv"
]

[tool.ruff.lint]
# Copied from docs
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default
# I -> isort.
# flake8-bugbear (`B`)
select = ["E4", "E7", "E9", "F", "I", "B"]
# BOO8 - https://docs.astral.sh/ruff/rules/function-call-in-default-argument/ (mostly ignoring for pydantic)
ignore = ["B008"]

# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
